version: "2"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  app1:
    container_name: app1
    image: httpd
    networks:
      - proxy-tier
    environment:
      VIRTUAL_HOST: "app1.exmaple.com"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 80
      CADDY_TLS: "off"
      CADDY_TIMEOUTS: "read 5m, write 2m"
    restart: always
