version: "2"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  app2:
    container_name: app2
    image: nginx
    networks:
      - proxy-tier
    environment:
      VIRTUAL_HOST: "app2.exmaple.com"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 80
      CADDY_TLS: "off"
      CADDY_TIMEOUTS: "read 1m, write 1m, header 1m, idle 1m"
    restart: always
