version: "2"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  app2:
    container_name: app2
    image: nginx
    networks:
      - proxy-tier
    environment:
      VIRTUAL_HOST: "app1.exmaple.com"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 80
    restart: always
